### ISSUE TITLE
option to preserve local copies of remotely-deleted messages

### ISSUE THREAD

**Issue by barak** [gauteh/lieer#125]
I'd like an option to tell lieer to keep local copies of any messages downloaded, even if they've been deleted remotely on gmail.

There are four reasons remote messages might have been deleted:

1. I did it because my quota is nearly full there
2. Someone broke into my gmail
3. I want to avoid google or legal authorities seeing them
4. They were in the spam folder and aged out of the 30-day spam retention window.

In the first three of these cases, I'd want to keep the local copies on my own machine.

Since spam is an exception, maybe there could be a way of applying to only not-in-spam-folder messages, or of doing a manual reap of local copies of deleted-on-remote messages which meet some criterion (like being between 30-40 days old and being marked spam), or some such.

Right now I get this functionality by periodically making a snapshot of the downloaded email, taking care to preserve sharing. But that's really not a very good solution.

**Comment by gauteh** [comment]
Sounds reasonable. There's an remove option, but I can't remember exactly
what it does at the moment. I think this would be best as a configuration
option? So that it is not accidentally forgotten.

fre. 27. des. 2019, 13:11 skrev Barak A. Pearlmutter <
notifications@github.com>:

**Comment by gauteh** [comment]
I probably won't have time to work on this in the near future, please feel
free to send a pull request.

fre. 27. des. 2019, 14:21 skrev Gaute Hope <eg@gaute.vetsj.com>:

**Comment by barak** [comment]
Agreed: configuration option seems like the right thing.

**Comment by gauteh** [comment]
The current behaviour is not consistent:

  * during full pull messages are only removed if `--remove` is
    specified.
  * during partial pull; a full pull is done if `--remove` is specified.
  * during partial pull: messages _are_ removed if deleted in the last
    changes, regardless of `--remove` option.

Suggested new behavior:

  * gmi set --remove-messages
  * gmi set --no-remove-messages

which controls the behavior for both cases. If you change it, you can
delete old un-removed messages by doing a full pull.

This will break for users doing `gmi pull --remove`, but that probably
didn't work the way people wanted anyway since `gmi pull` would remove
messages if doing a partial pull anyway.

**Comment by gauteh** [comment]
Please test out #148.
