### ISSUE TITLE
gmi push takes hours every time

### ISSUE THREAD

**Issue by kode54** [gauteh/lieer#240]
I have 425k messages on my remote side, and it apparently has to fetch the metadata for all of them, every single time. Is there some way this can be sped up?

**Comment by gauteh** [comment]
You can try the resume option on the initial sync. Gmi needs a full initial
sync.

søn. 28. mai 2023, 13:51 skrev Christopher Snowhill <
***@***.***>:

**Comment by kode54** [comment]
I already have a full initial sync. It does a full metadata fetch every time I run sync after that.

**Comment by gauteh** [comment]
No, that should be fine. But if the historyId is out-of-bounds gmi needs to do a full sync as well. This usually happens if you haven't run gmi for a long while, but can also happen if you make a lot of changes outside gmi.

The usual reason for this problem though is that the full sync somehow is not fully completed. Then the experience can be a bit better with the resume option (in case the full sync is interrupted).

You can also consider making your own API key, this should make things a bit faster. But I haven't tried that in a long time so I don't know exactly how that works nowadays.

**Comment by kode54** [comment]
Yeah, I'm using my own API key, or at least my own OAuth2 secrets. Seems there's only the usual GMail throttling of 250 event points per second, sliding average. Here, it usually manages about 35 seconds of uninterrupted metadata downloading at about 160it/s, then it throttles. This repeats in cycles of approximately two minutes.

**Comment by kode54** [comment]
Sorry about this. It turns out there was a huge mess of data to finally sync properly, because of the accident of having new.tags unset in my config, which resulted in all my new mail getting +inbox and +unread, which I needed to reconcile. After all the removal of the local tags, and the syncing, and some deletion of old mail (after archiving it to another notmuch config on spinning rust, specifically indexed for archival purposes), the sync process completes almost immediately.

**Comment by gauteh** [comment]
Good to hear!

søn. 4. jun. 2023, 10:48 skrev Christopher Snowhill <
***@***.***>:
